### ISSUE TITLE
Seasonal Typology

### ISSUE THREAD

**Issue by mirahx24** [BHoM/LadybugTools_Toolkit#120]
Enable different typologies for different season in one spatial comfort calc. For example, be able to apply Overhang Shelter only during the summer time / daytime and apply Wind Shelter only during the winter time/night. 
![image](https://github.com/BHoM/LadybugTools_Toolkit/assets/14883017/90e3665d-5889-468c-849c-2a25bf7e7315)

**Comment by tg359** [comment]
@mirahx24 following a few changes in the code, this should now be possible. The shelter objects can be given a list of porosity values instead which very per-timestep and enable this to happen 👍 (the same is also true of the inputs to the Typology, where evaporative_cooling_effect and the other inputs can be a list of values)
