### ISSUE TITLE
Refactor serialisation of python inputs/outputs

### ISSUE THREAD

**Issue by Tom-Kingstone** [BHoM/LadybugTools_Toolkit#136]
#### Description:

Move serialisation into an adapter so that their methods are hidden from the user.
- Create methods that convert BHoM objects to python readable json files.
- Read methods for converting from python json file output to BHoM objects.

**Comment by tg359** [comment]
@Tom-Kingstone here are a bunch of pre-serialised files for testing of this. Many object conversions not in there yet, but I've also included some geometries in here which would mean that we could interop with other LB/HB workflows.

[SerialisedLBHBobjects.zip](https://github.com/BHoM/LadybugTools_Toolkit/files/13376559/SerialisedLBHBobjects.zip)
