### ISSUE TITLE
Change references to C:/ProgramData

### ISSUE THREAD

**Issue by Tom-Kingstone** [BHoM/LadybugTools_Toolkit#137]
#### Broken rules:

references to C:/ProgramData can fail in cases where a user has their ProgramData folder in D:/

#### Suggestions to restore compliance:

Change references of C:/ProgramData to common ProgramData - using `GetFolderPath` with `CommonApplicationData` (as shown by @FraserGreenroyd in #134)

**Comment by FraserGreenroyd** [comment]
https://github.com/BHoM/LadybugTools_Toolkit/pull/134#discussion_r1392326173

Link to specific comment for ease of finding.
