### ISSUE TITLE
Enable adapter workflows with varying "datatype" types

### ISSUE THREAD

**Issue by tg359** [BHoM/LadybugTools_Toolkit#146]
#### Description:

DataType objects can be dynamic with fields varying based on what "type" it represents (yay Python). For C# this gets tricky, but by having a GenericDataType and a DataType we should be able to handle both forms.

**Comment by Tom-Kingstone** [comment]
We can actually handle both forms in the current `DataType` object already defined. This just means slightly changing the serialiser to reflect the different types (as the python side objects have lots of redundancy).
