### ISSUE TITLE
Add internal mass to ground zone simulation

### ISSUE THREAD

**Issue by tg359** [BHoM/LadybugTools_Toolkit#188]
#### Description:

Add InternalMass to ground zone creation part that feeds into SimulationResult process to get surface temperatures to replicate more accurate ground conditions.

https://github.com/BHoM/LadybugTools_Toolkit/blob/442c0435be27aca0710d0d576d644f73aa73fa5b/LadybugTools_Engine/Python/src/ladybugtools_toolkit/external_comfort/model.py#L75

![image](https://github.com/BHoM/LadybugTools_Toolkit/assets/10939984/32c4cc6d-1bde-4205-b9d3-7dd1cf1a35d4)

**Comment by Erida-Bendo** [comment]
I had a go at this while trying to get more acquainted with the toolkit. I linked the branch where I did the changes to this issue. Not sure if I am applying the InternalMass construction the right way.
