### ISSUE TITLE
LadybugTools_Toolkit: Review or remove FromHoneyBeeSurface

### ISSUE THREAD

**Issue by jamesramsden-bh** [BHoM/LadybugTools_Toolkit#48]
#### Broken rules:
FromHoneyBeeSurface currently takes in a honeybeeSrf type, which appears to no longer be a valid type in newer versions of Honeybee. 

#### Suggestions to restore compliance:
Update this method for a current surface type, or remove the method altogether.

**Comment by Tom-Kingstone** [comment]
The method was removed as part of the 7.0 beta in #124, but was missed for closure.
